pipeline_name: postos_abastecimento_ingestion

source:
  name: DGEG
  type: api
  url: https://servergeo.dgeg.gov.pt/arcgis/services/Visualizadores/PACVR/MapServer/WFSServer?request=GetFeature&service=WFS&typename=PACVR:Postos_Abastecimento&outputFormat=GEOJSON

destinations:
  - type: crate
    name: CrateDB
    host: https://cmmaia-xavier.aks1.westeurope.azure.cratedb.net:4200
    database: crate
    table: postos_abastecimento
    username: admin
    password: $CRATEDB_PASSWORD

  - type: mysql
    name: Aiven
    host: cmmaia-xavier-xavierkooijman-e96b.f.aivencloud.com
    port: 23850
    database: defaultdb
    table: postos_abastecimento
    username: avnadmin
    password: $AIVEN_PASSWORD

  - type: mysql
    name: TiDB Cloud
    host: gateway01.eu-central-1.prod.aws.tidbcloud.com
    port: 4000
    database: test
    table: postos_abastecimento
    username: 495NGCCkPoossRz.root
    password: $TIDB_PASSWORD
    certificate: isrgrootx1.pem

save_raw: false

email:
  send: true
  from: cmmaiaxavier@gmail.com
  password: $EMAIL_PASSWORD
  api_key: $RESEND_API_KEY
  subject: Postos Abastecimento DGEG Ingestion Pipeline Report
  recipients:
    - cmmaiaxavier@gmail.com
    - xavierkooijman@gmail.com
